export { FontFamily } from './FontFamily'
export { FontSize } from './FontSize'
export { LineHeight } from './LineHeight'
export { LetterSpacing } from './LetterSpacing'
export { BackgroundColor } from './BackgroundColor'
export { TextColor } from './TextColor'
