export const primaryFonts = [
  'DotGothic16',
  'Fascinate',
  'Hina Mincho',
  'IBM Plex Mono',
  'Inter',
  'Klee One',
  'M PLUS Rounded 1c',
  'Mochiy Pop P One',
  'Montagu Slab',
  'New Tegomin',
  'Noto Sans JP',
  'Noto Serif JP',
  'Pacifico',
  'Potta One',
  'Press Start 2P',
  'Rampart One',
  'Rubik Moonrocks',
  'Sawarabi Gothic',
  'Sawarabi Mincho',
  'Shippori Mincho',
  'Zen Antique Soft',
  'Zen Kaku Gothic New',
]
