export type { CategoryContentType } from './Category'
export type { DataTableContentType } from './DataTable'
export type { LinksContentType } from './Links'
export type { OverviewContentType } from './Overview'
export type { PhotosContentType } from './Photos'
export type { PostContentType } from './Post'
export type { BiographyContentType } from './Biography'
